export const TASKS = 'TASKS'
export const ADD_TASK = 'ADD_TASK'
export const UPDATE_TASK = 'UPDATE_TASK'
export const DELETE_TASK = 'DELETE_TASK'
export const SET_FILTERED_TASKS = 'SET_FILTERED_TASKS'
